CREATE DATABASE ITM
GO
USE ITM
GO
CREATE TABLE Account
(
	AccountID		VARCHAR(50)	NOT NULL PRIMARY KEY,
	CustomerName	VARCHAR(50)	NOT NULL,
	Email			VARCHAR(50)	NOT NULL,
	Phone			VARCHAR(50)	NOT NULL,
	Balance			INT			NOT NULL
)
GO
CREATE TABLE TransactionDetails
(
	TranID			INT PRIMARY KEY IDENTITY(1,1),
	AccountID		VARCHAR(50)	NOT NULL,
	TranMoney		INT	NOT NULL,
	TranType		INT NOT NULL,
	DateOfTran		VARCHAR(50)
)
